/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReadingCoachPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/ai/prompts/en.ts
var PromptsEN = {
  depthCheck: (sourceText, userNotes) => {
    return `You are a reading comprehension coach. Analyze the user's notes against the source text and provide a depth analysis.

SOURCE TEXT:
${sourceText}

USER'S NOTES:
${userNotes}

Analyze the depth of understanding demonstrated in the notes. Provide:
1. Overall comprehension level (surface/moderate/deep)
2. Key concepts captured vs missed
3. Areas needing deeper exploration
4. Specific suggestions for improvement

Respond in the same language as the source text and notes. Format your response as a structured analysis.`;
  },
  connectionFinder: (sourceText, userNotes, vaultNotes) => {
    return `You are a reading comprehension coach. Find connections between the user's current notes and their existing vault notes.

SOURCE TEXT:
${sourceText}

USER'S CURRENT NOTES:
${userNotes}

EXISTING VAULT NOTES (titles):
${vaultNotes.join("\n")}

Identify:
1. Related notes in the vault that connect to this topic
2. Potential knowledge gaps that could be filled by linking notes
3. Suggestions for creating new connections
4. Conceptual bridges between current and existing knowledge

Respond in the same language as the source text and notes. Format your response as a connection map.`;
  }
};

// src/ai/prompts/ru.ts
var PromptsRU = {
  depthCheck: (sourceText, userNotes) => {
    return `\u0422\u044B \u2014 \u0442\u0440\u0435\u043D\u0435\u0440 \u043F\u043E \u043F\u043E\u043D\u0438\u043C\u0430\u043D\u0438\u044E \u043F\u0440\u043E\u0447\u0438\u0442\u0430\u043D\u043D\u043E\u0433\u043E. \u041F\u0440\u043E\u0430\u043D\u0430\u043B\u0438\u0437\u0438\u0440\u0443\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u043E\u0442\u043D\u043E\u0441\u0438\u0442\u0435\u043B\u044C\u043D\u043E \u0438\u0441\u0445\u043E\u0434\u043D\u043E\u0433\u043E \u0442\u0435\u043A\u0441\u0442\u0430 \u0438 \u043F\u0440\u0435\u0434\u043E\u0441\u0442\u0430\u0432\u044C \u0430\u043D\u0430\u043B\u0438\u0437 \u0433\u043B\u0443\u0431\u0438\u043D\u044B \u043F\u043E\u043D\u0438\u043C\u0430\u043D\u0438\u044F.

\u0418\u0421\u0425\u041E\u0414\u041D\u042B\u0419 \u0422\u0415\u041A\u0421\u0422:
${sourceText}

\u0417\u0410\u041C\u0415\u0422\u041A\u0418 \u041F\u041E\u041B\u042C\u0417\u041E\u0412\u0410\u0422\u0415\u041B\u042F:
${userNotes}

\u041F\u0440\u043E\u0430\u043D\u0430\u043B\u0438\u0437\u0438\u0440\u0443\u0439 \u0433\u043B\u0443\u0431\u0438\u043D\u0443 \u043F\u043E\u043D\u0438\u043C\u0430\u043D\u0438\u044F, \u043F\u0440\u043E\u0434\u0435\u043C\u043E\u043D\u0441\u0442\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u0443\u044E \u0432 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u0445. \u041F\u0440\u0435\u0434\u043E\u0441\u0442\u0430\u0432\u044C:
1. \u041E\u0431\u0449\u0438\u0439 \u0443\u0440\u043E\u0432\u0435\u043D\u044C \u043F\u043E\u043D\u0438\u043C\u0430\u043D\u0438\u044F (\u043F\u043E\u0432\u0435\u0440\u0445\u043D\u043E\u0441\u0442\u043D\u044B\u0439/\u0441\u0440\u0435\u0434\u043D\u0438\u0439/\u0433\u043B\u0443\u0431\u043E\u043A\u0438\u0439)
2. \u041A\u043B\u044E\u0447\u0435\u0432\u044B\u0435 \u043A\u043E\u043D\u0446\u0435\u043F\u0446\u0438\u0438: \u0447\u0442\u043E \u0443\u043B\u043E\u0432\u043B\u0435\u043D\u043E, \u0447\u0442\u043E \u0443\u043F\u0443\u0449\u0435\u043D\u043E
3. \u041E\u0431\u043B\u0430\u0441\u0442\u0438, \u0442\u0440\u0435\u0431\u0443\u044E\u0449\u0438\u0435 \u0431\u043E\u043B\u0435\u0435 \u0433\u043B\u0443\u0431\u043E\u043A\u043E\u0433\u043E \u0438\u0437\u0443\u0447\u0435\u043D\u0438\u044F
4. \u041A\u043E\u043D\u043A\u0440\u0435\u0442\u043D\u044B\u0435 \u0440\u0435\u043A\u043E\u043C\u0435\u043D\u0434\u0430\u0446\u0438\u0438 \u043F\u043E \u0443\u043B\u0443\u0447\u0448\u0435\u043D\u0438\u044E

\u041E\u0442\u0432\u0435\u0447\u0430\u0439 \u043D\u0430 \u0442\u043E\u043C \u0436\u0435 \u044F\u0437\u044B\u043A\u0435, \u0447\u0442\u043E \u0438 \u0438\u0441\u0445\u043E\u0434\u043D\u044B\u0439 \u0442\u0435\u043A\u0441\u0442 \u0441 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438. \u041E\u0444\u043E\u0440\u043C\u0438 \u043E\u0442\u0432\u0435\u0442 \u0432 \u0432\u0438\u0434\u0435 \u0441\u0442\u0440\u0443\u043A\u0442\u0443\u0440\u0438\u0440\u043E\u0432\u0430\u043D\u043D\u043E\u0433\u043E \u0430\u043D\u0430\u043B\u0438\u0437\u0430.`;
  },
  connectionFinder: (sourceText, userNotes, vaultNotes) => {
    return `\u0422\u044B \u2014 \u0442\u0440\u0435\u043D\u0435\u0440 \u043F\u043E \u043F\u043E\u043D\u0438\u043C\u0430\u043D\u0438\u044E \u043F\u0440\u043E\u0447\u0438\u0442\u0430\u043D\u043D\u043E\u0433\u043E. \u041D\u0430\u0439\u0434\u0438 \u0441\u0432\u044F\u0437\u0438 \u043C\u0435\u0436\u0434\u0443 \u0442\u0435\u043A\u0443\u0449\u0438\u043C\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u0438 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044E\u0449\u0438\u043C\u0438 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438 \u0432 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0435.

\u0418\u0421\u0425\u041E\u0414\u041D\u042B\u0419 \u0422\u0415\u041A\u0421\u0422:
${sourceText}

\u0422\u0415\u041A\u0423\u0429\u0418\u0415 \u0417\u0410\u041C\u0415\u0422\u041A\u0418 \u041F\u041E\u041B\u042C\u0417\u041E\u0412\u0410\u0422\u0415\u041B\u042F:
${userNotes}

\u0421\u0423\u0429\u0415\u0421\u0422\u0412\u0423\u042E\u0429\u0418\u0415 \u0417\u0410\u041C\u0415\u0422\u041A\u0418 \u0412 \u0425\u0420\u0410\u041D\u0418\u041B\u0418\u0429\u0415 (\u043D\u0430\u0437\u0432\u0430\u043D\u0438\u044F):
${vaultNotes.join("\n")}

\u041E\u043F\u0440\u0435\u0434\u0435\u043B\u0438:
1. \u0421\u0432\u044F\u0437\u0430\u043D\u043D\u044B\u0435 \u0437\u0430\u043C\u0435\u0442\u043A\u0438 \u0432 \u0445\u0440\u0430\u043D\u0438\u043B\u0438\u0449\u0435, \u043A\u043E\u0442\u043E\u0440\u044B\u0435 \u043E\u0442\u043D\u043E\u0441\u044F\u0442\u0441\u044F \u043A \u044D\u0442\u043E\u0439 \u0442\u0435\u043C\u0435
2. \u041F\u043E\u0442\u0435\u043D\u0446\u0438\u0430\u043B\u044C\u043D\u044B\u0435 \u043F\u0440\u043E\u0431\u0435\u043B\u044B \u0432 \u0437\u043D\u0430\u043D\u0438\u044F\u0445, \u043A\u043E\u0442\u043E\u0440\u044B\u0435 \u043C\u043E\u0436\u043D\u043E \u0437\u0430\u043F\u043E\u043B\u043D\u0438\u0442\u044C \u0441\u0432\u044F\u0437\u044B\u0432\u0430\u043D\u0438\u0435\u043C \u0437\u0430\u043C\u0435\u0442\u043E\u043A
3. \u041F\u0440\u0435\u0434\u043B\u043E\u0436\u0435\u043D\u0438\u044F \u043F\u043E \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u044E \u043D\u043E\u0432\u044B\u0445 \u0441\u0432\u044F\u0437\u0435\u0439
4. \u041A\u043E\u043D\u0446\u0435\u043F\u0442\u0443\u0430\u043B\u044C\u043D\u044B\u0435 \u043C\u043E\u0441\u0442\u044B \u043C\u0435\u0436\u0434\u0443 \u0442\u0435\u043A\u0443\u0449\u0438\u043C\u0438 \u0438 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u044E\u0449\u0438\u043C\u0438 \u0437\u043D\u0430\u043D\u0438\u044F\u043C\u0438

\u041E\u0442\u0432\u0435\u0447\u0430\u0439 \u043D\u0430 \u0442\u043E\u043C \u0436\u0435 \u044F\u0437\u044B\u043A\u0435, \u0447\u0442\u043E \u0438 \u0438\u0441\u0445\u043E\u0434\u043D\u044B\u0439 \u0442\u0435\u043A\u0441\u0442 \u0441 \u0437\u0430\u043C\u0435\u0442\u043A\u0430\u043C\u0438. \u041E\u0444\u043E\u0440\u043C\u0438 \u043E\u0442\u0432\u0435\u0442 \u0432 \u0432\u0438\u0434\u0435 \u043A\u0430\u0440\u0442\u044B \u0441\u0432\u044F\u0437\u0435\u0439.`;
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  promptLanguage: "auto",
  customPrompts: {
    depthCheckEN: "",
    depthCheckRU: "",
    connectionFinderEN: "",
    connectionFinderRU: ""
  },
  aiProvider: "openai",
  openaiApiKey: "",
  openaiModel: "gpt-3.5-turbo",
  ollamaUrl: "http://localhost:11434",
  ollamaModel: "llama2",
  deepseekApiKey: "",
  deepseekModel: "deepseek-chat",
  openrouterApiKey: "",
  openrouterModel: "anthropic/claude-2",
  depthCheckEnabled: true,
  connectionFinderEnabled: true,
  temperature: 0.7
};
var ReadingCoachSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Reading Coach Settings" });
    new import_obsidian.Setting(containerEl).setName("Prompt Language").setDesc("Language for AI prompts (Auto detects from content)").addDropdown((dropdown) => dropdown.addOption("auto", "Auto-detect").addOption("en", "English").addOption("ru", "\u0420\u0443\u0441\u0441\u043A\u0438\u0439").setValue(this.plugin.settings.promptLanguage).onChange(async (value) => {
      this.plugin.settings.promptLanguage = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("AI Provider").setDesc("Choose your AI provider").addDropdown((dropdown) => dropdown.addOption("openai", "OpenAI").addOption("ollama", "Ollama (Local)").addOption("deepseek", "DeepSeek").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
      this.plugin.settings.aiProvider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.aiProvider === "openai") {
      containerEl.createEl("h3", { text: "OpenAI Configuration" });
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Enter your OpenAI API key").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Model").setDesc("OpenAI model to use").addDropdown((dropdown) => dropdown.addOption("gpt-3.5-turbo", "GPT-3.5 Turbo").addOption("gpt-4", "GPT-4").addOption("gpt-4-turbo", "GPT-4 Turbo").setValue(this.plugin.settings.openaiModel).onChange(async (value) => {
        this.plugin.settings.openaiModel = value;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.aiProvider === "ollama") {
      containerEl.createEl("h3", { text: "Ollama Configuration" });
      new import_obsidian.Setting(containerEl).setName("Ollama URL").setDesc("URL of your local Ollama instance").addText((text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaUrl).onChange(async (value) => {
        this.plugin.settings.ollamaUrl = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Model").setDesc("Ollama model to use (e.g., llama2, mistral)").addText((text) => text.setPlaceholder("llama2").setValue(this.plugin.settings.ollamaModel).onChange(async (value) => {
        this.plugin.settings.ollamaModel = value;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.aiProvider === "deepseek") {
      containerEl.createEl("h3", { text: "DeepSeek Configuration" });
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Enter your DeepSeek API key").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Model").setDesc("DeepSeek model to use").addText((text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.deepseekModel).onChange(async (value) => {
        this.plugin.settings.deepseekModel = value;
        await this.plugin.saveSettings();
      }));
    }
    if (this.plugin.settings.aiProvider === "openrouter") {
      containerEl.createEl("h3", { text: "OpenRouter Configuration" });
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Enter your OpenRouter API key").addText((text) => text.setPlaceholder("sk-or-...").setValue(this.plugin.settings.openrouterApiKey).onChange(async (value) => {
        this.plugin.settings.openrouterApiKey = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("Model").setDesc("OpenRouter model to use").addText((text) => text.setPlaceholder("anthropic/claude-2").setValue(this.plugin.settings.openrouterModel).onChange(async (value) => {
        this.plugin.settings.openrouterModel = value;
        await this.plugin.saveSettings();
      }));
    }
    containerEl.createEl("h3", { text: "AI Parameters" });
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc("Controls randomness (0.0 = focused, 1.0 = creative)").addSlider((slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.temperature = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Enabled Modes" });
    new import_obsidian.Setting(containerEl).setName("Depth Check").setDesc("Analyze understanding depth of your notes").addToggle((toggle) => toggle.setValue(this.plugin.settings.depthCheckEnabled).onChange(async (value) => {
      this.plugin.settings.depthCheckEnabled = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Connection Finder").setDesc("Find connections between notes in your vault").addToggle((toggle) => toggle.setValue(this.plugin.settings.connectionFinderEnabled).onChange(async (value) => {
      this.plugin.settings.connectionFinderEnabled = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Custom Prompts" });
    containerEl.createEl("p", {
      text: "Customize AI prompts for each mode. Leave empty to use defaults. Use {sourceText}, {userNotes}, and {vaultNotes} as placeholders.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Depth Check Prompt (English)").setDesc("Custom prompt for Depth Check mode in English").addTextArea((text) => {
      text.setPlaceholder("Leave empty for default prompt").setValue(this.plugin.settings.customPrompts.depthCheckEN).onChange(async (value) => {
        this.plugin.settings.customPrompts.depthCheckEN = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
    });
    new import_obsidian.Setting(containerEl).setName("").addButton((button) => button.setButtonText("Show Default EN Prompt").onClick(() => {
      const defaultPrompt = PromptsEN.depthCheck("{sourceText}", "{userNotes}");
      new PromptPreviewModal(this.app, "Default Depth Check Prompt (EN)", defaultPrompt).open();
    }));
    new import_obsidian.Setting(containerEl).setName("Depth Check Prompt (Russian)").setDesc("Custom prompt for Depth Check mode in Russian").addTextArea((text) => {
      text.setPlaceholder("\u041E\u0441\u0442\u0430\u0432\u044C\u0442\u0435 \u043F\u0443\u0441\u0442\u044B\u043C \u0434\u043B\u044F \u043F\u0440\u043E\u043C\u043F\u0442\u0430 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setValue(this.plugin.settings.customPrompts.depthCheckRU).onChange(async (value) => {
        this.plugin.settings.customPrompts.depthCheckRU = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
    });
    new import_obsidian.Setting(containerEl).setName("").addButton((button) => button.setButtonText("Show Default RU Prompt").onClick(() => {
      const defaultPrompt = PromptsRU.depthCheck("{sourceText}", "{userNotes}");
      new PromptPreviewModal(this.app, "Default Depth Check Prompt (RU)", defaultPrompt).open();
    }));
    new import_obsidian.Setting(containerEl).setName("Connection Finder Prompt (English)").setDesc("Custom prompt for Connection Finder mode in English").addTextArea((text) => {
      text.setPlaceholder("Leave empty for default prompt").setValue(this.plugin.settings.customPrompts.connectionFinderEN).onChange(async (value) => {
        this.plugin.settings.customPrompts.connectionFinderEN = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
    });
    new import_obsidian.Setting(containerEl).setName("").addButton((button) => button.setButtonText("Show Default EN Prompt").onClick(() => {
      const defaultPrompt = PromptsEN.connectionFinder("{sourceText}", "{userNotes}", ["{vaultNotes}"]);
      new PromptPreviewModal(this.app, "Default Connection Finder Prompt (EN)", defaultPrompt).open();
    }));
    new import_obsidian.Setting(containerEl).setName("Connection Finder Prompt (Russian)").setDesc("Custom prompt for Connection Finder mode in Russian").addTextArea((text) => {
      text.setPlaceholder("\u041E\u0441\u0442\u0430\u0432\u044C\u0442\u0435 \u043F\u0443\u0441\u0442\u044B\u043C \u0434\u043B\u044F \u043F\u0440\u043E\u043C\u043F\u0442\u0430 \u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E").setValue(this.plugin.settings.customPrompts.connectionFinderRU).onChange(async (value) => {
        this.plugin.settings.customPrompts.connectionFinderRU = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 8;
      text.inputEl.cols = 50;
    });
    new import_obsidian.Setting(containerEl).setName("").addButton((button) => button.setButtonText("Show Default RU Prompt").onClick(() => {
      const defaultPrompt = PromptsRU.connectionFinder("{sourceText}", "{userNotes}", ["{vaultNotes}"]);
      new PromptPreviewModal(this.app, "Default Connection Finder Prompt (RU)", defaultPrompt).open();
    }));
  }
};
var PromptPreviewModal = class extends import_obsidian.Modal {
  constructor(app, title, content) {
    super(app);
    this.title = title;
    this.content = content;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.title });
    const pre = contentEl.createEl("pre", {
      text: this.content,
      cls: "reading-coach-prompt-preview"
    });
    pre.style.whiteSpace = "pre-wrap";
    pre.style.maxHeight = "400px";
    pre.style.overflow = "auto";
    pre.style.padding = "1em";
    pre.style.backgroundColor = "var(--background-secondary)";
    pre.style.borderRadius = "4px";
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/modes/depthCheck.ts
var import_obsidian3 = require("obsidian");

// src/ai/provider.ts
var AIProvider = class {
  constructor(settings) {
    this.settings = settings;
  }
  async generate(prompt) {
    try {
      switch (this.settings.aiProvider) {
        case "openai":
          return await this.callOpenAI(prompt);
        case "ollama":
          return await this.callOllama(prompt);
        case "deepseek":
          return await this.callDeepSeek(prompt);
        case "openrouter":
          return await this.callOpenRouter(prompt);
        default:
          return { content: "", error: "Unknown AI provider" };
      }
    } catch (error) {
      return { content: "", error: error.message };
    }
  }
  async callOpenAI(prompt) {
    if (!this.settings.openaiApiKey) {
      throw new Error("OpenAI API key not configured");
    }
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.openaiApiKey}`
      },
      body: JSON.stringify({
        model: this.settings.openaiModel,
        messages: [{ role: "user", content: prompt }],
        temperature: this.settings.temperature
      })
    });
    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.statusText}`);
    }
    const data = await response.json();
    return { content: data.choices[0].message.content };
  }
  async callOllama(prompt) {
    const response = await fetch(`${this.settings.ollamaUrl}/api/generate`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: this.settings.ollamaModel,
        prompt,
        stream: false,
        options: {
          temperature: this.settings.temperature
        }
      })
    });
    if (!response.ok) {
      throw new Error(`Ollama API error: ${response.statusText}`);
    }
    const data = await response.json();
    return { content: data.response };
  }
  async callDeepSeek(prompt) {
    if (!this.settings.deepseekApiKey) {
      throw new Error("DeepSeek API key not configured");
    }
    const response = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.deepseekApiKey}`
      },
      body: JSON.stringify({
        model: this.settings.deepseekModel,
        messages: [{ role: "user", content: prompt }],
        temperature: this.settings.temperature
      })
    });
    if (!response.ok) {
      throw new Error(`DeepSeek API error: ${response.statusText}`);
    }
    const data = await response.json();
    return { content: data.choices[0].message.content };
  }
  async callOpenRouter(prompt) {
    if (!this.settings.openrouterApiKey) {
      throw new Error("OpenRouter API key not configured");
    }
    const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.settings.openrouterApiKey}`,
        "HTTP-Referer": "https://github.com/yourusername/reading-coach",
        "X-Title": "Reading Coach"
      },
      body: JSON.stringify({
        model: this.settings.openrouterModel,
        messages: [{ role: "user", content: prompt }],
        temperature: this.settings.temperature
      })
    });
    if (!response.ok) {
      throw new Error(`OpenRouter API error: ${response.statusText}`);
    }
    const data = await response.json();
    return { content: data.choices[0].message.content };
  }
};

// src/ai/prompts.ts
var Prompts = class {
  static depthCheck(sourceText, userNotes, language = "en", customPrompt) {
    if (customPrompt && customPrompt.trim()) {
      return customPrompt.replace(/{sourceText}/g, sourceText).replace(/{userNotes}/g, userNotes);
    }
    return language === "ru" ? PromptsRU.depthCheck(sourceText, userNotes) : PromptsEN.depthCheck(sourceText, userNotes);
  }
  static connectionFinder(sourceText, userNotes, vaultNotes, language = "en", customPrompt) {
    if (customPrompt && customPrompt.trim()) {
      return customPrompt.replace(/{sourceText}/g, sourceText).replace(/{userNotes}/g, userNotes).replace(/{vaultNotes}/g, vaultNotes.join("\n"));
    }
    return language === "ru" ? PromptsRU.connectionFinder(sourceText, userNotes, vaultNotes) : PromptsEN.connectionFinder(sourceText, userNotes, vaultNotes);
  }
};

// src/views/resultModal.ts
var import_obsidian2 = require("obsidian");
var ResultModal = class extends import_obsidian2.Modal {
  constructor(app, title, content) {
    super(app);
    this.title = title;
    this.content = content;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("reading-coach-modal");
    const header = contentEl.createDiv({ cls: "reading-coach-modal-header" });
    header.createEl("h2", { text: this.title });
    const contentDiv = contentEl.createDiv({ cls: "reading-coach-modal-content" });
    import_obsidian2.MarkdownRenderer.renderMarkdown(
      this.content,
      contentDiv,
      "",
      null
    );
    const footer = contentEl.createDiv({ cls: "reading-coach-modal-footer" });
    const closeBtn = footer.createEl("button", { text: "Close", cls: "mod-cta" });
    closeBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/utils/languageDetector.ts
var LanguageDetector = class {
  static detect(text) {
    const cyrillicCount = (text.match(/[\u0400-\u04FF]/g) || []).length;
    const latinCount = (text.match(/[a-zA-Z]/g) || []).length;
    return cyrillicCount > latinCount ? "ru" : "en";
  }
  static detectFromBoth(sourceText, userNotes) {
    const sourceLang = this.detect(sourceText);
    const notesLang = this.detect(userNotes);
    if (sourceLang === notesLang) {
      return sourceLang;
    }
    return sourceLang;
  }
};
LanguageDetector.CYRILLIC_PATTERN = /[\u0400-\u04FF]/;
LanguageDetector.LATIN_PATTERN = /[a-zA-Z]/;

// src/modes/depthCheck.ts
var DepthCheckMode = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async execute(sourceText, userNotes) {
    if (!this.plugin.settings.depthCheckEnabled) {
      new import_obsidian3.Notice("Depth Check mode is disabled in settings");
      return;
    }
    new import_obsidian3.Notice("Analyzing depth of understanding...");
    const detectedLang = LanguageDetector.detectFromBoth(sourceText, userNotes);
    const lang = this.plugin.settings.promptLanguage === "auto" ? detectedLang : this.plugin.settings.promptLanguage;
    const provider = new AIProvider(this.plugin.settings);
    const customPrompt = lang === "ru" ? this.plugin.settings.customPrompts.depthCheckRU : this.plugin.settings.customPrompts.depthCheckEN;
    const prompt = Prompts.depthCheck(sourceText, userNotes, lang, customPrompt);
    const response = await provider.generate(prompt);
    if (response.error) {
      new import_obsidian3.Notice(`Error: ${response.error}`);
      return;
    }
    new ResultModal(this.plugin.app, "Depth Check Analysis", response.content).open();
  }
};

// src/modes/connectionFinder.ts
var import_obsidian4 = require("obsidian");

// src/utils/vaultScanner.ts
var VaultScanner = class {
  constructor(app) {
    this.app = app;
  }
  async getAllNoteTitles() {
    const files = this.app.vault.getMarkdownFiles();
    return files.map((file) => file.basename);
  }
  async getAllNotes() {
    return this.app.vault.getMarkdownFiles();
  }
  async getNoteContent(file) {
    return await this.app.vault.read(file);
  }
};

// src/modes/connectionFinder.ts
var ConnectionFinderMode = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  async execute(sourceText, userNotes) {
    if (!this.plugin.settings.connectionFinderEnabled) {
      new import_obsidian4.Notice("Connection Finder mode is disabled in settings");
      return;
    }
    new import_obsidian4.Notice("Scanning vault and finding connections...");
    const scanner = new VaultScanner(this.plugin.app);
    const vaultNotes = await scanner.getAllNoteTitles();
    const detectedLang = LanguageDetector.detectFromBoth(sourceText, userNotes);
    const lang = this.plugin.settings.promptLanguage === "auto" ? detectedLang : this.plugin.settings.promptLanguage;
    const provider = new AIProvider(this.plugin.settings);
    const customPrompt = lang === "ru" ? this.plugin.settings.customPrompts.connectionFinderRU : this.plugin.settings.customPrompts.connectionFinderEN;
    const prompt = Prompts.connectionFinder(sourceText, userNotes, vaultNotes, lang, customPrompt);
    const response = await provider.generate(prompt);
    if (response.error) {
      new import_obsidian4.Notice(`Error: ${response.error}`);
      return;
    }
    new ResultModal(this.plugin.app, "Connection Finder", response.content).open();
  }
};

// src/views/sourceInputModal.ts
var import_obsidian5 = require("obsidian");

// src/utils/textExtractor.ts
var TextExtractor = class {
  static async extractFromUrl(url) {
    try {
      new URL(url);
    } catch (e) {
      throw new Error("Invalid URL format");
    }
    try {
      const response = await fetch(url, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
        }
      });
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
      const contentType = response.headers.get("content-type");
      if (!contentType || !contentType.includes("text/html")) {
        throw new Error("URL does not point to an HTML page");
      }
      const html = await response.text();
      const text = this.parseHtml(html);
      if (!text || text.length < 100) {
        throw new Error("Could not extract meaningful text from the page");
      }
      return text;
    } catch (error) {
      throw new Error(`Failed to fetch article: ${error.message}`);
    }
  }
  static extractFromText(text) {
    return text.trim();
  }
  static parseHtml(html) {
    let text = html.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "").replace(/<style[^>]*>[\s\S]*?<\/style>/gi, "").replace(/<noscript[^>]*>[\s\S]*?<\/noscript>/gi, "").replace(/<nav[^>]*>[\s\S]*?<\/nav>/gi, "").replace(/<header[^>]*>[\s\S]*?<\/header>/gi, "").replace(/<footer[^>]*>[\s\S]*?<\/footer>/gi, "").replace(/<aside[^>]*>[\s\S]*?<\/aside>/gi, "");
    let extractedText = "";
    const articleMatch = text.match(/<article[^>]*>([\s\S]*?)<\/article>/i);
    if (articleMatch) {
      extractedText = articleMatch[1];
    }
    if (!extractedText) {
      const mainMatch = text.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
      if (mainMatch) {
        extractedText = mainMatch[1];
      }
    }
    if (!extractedText) {
      const patterns = [
        /<div[^>]*class="[^"]*article[^"]*"[^>]*>([\s\S]*?)<\/div>/i,
        /<div[^>]*class="[^"]*content[^"]*"[^>]*>([\s\S]*?)<\/div>/i,
        /<div[^>]*class="[^"]*post[^"]*"[^>]*>([\s\S]*?)<\/div>/i,
        /<div[^>]*class="[^"]*entry[^"]*"[^>]*>([\s\S]*?)<\/div>/i,
        /<div[^>]*class="[^"]*text[^"]*"[^>]*>([\s\S]*?)<\/div>/i,
        /<div[^>]*itemprop="articleBody"[^>]*>([\s\S]*?)<\/div>/i
      ];
      for (const pattern of patterns) {
        const match = text.match(pattern);
        if (match && match[1].length > 200) {
          extractedText = match[1];
          break;
        }
      }
    }
    if (!extractedText) {
      const bodyMatch = text.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
      if (bodyMatch) {
        extractedText = bodyMatch[1];
      } else {
        extractedText = text;
      }
    }
    extractedText = extractedText.replace(/<[^>]+>/g, " ").replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&mdash;/g, "\u2014").replace(/&ndash;/g, "\u2013").replace(/&hellip;/g, "\u2026").replace(/&#\d+;/g, "").replace(/&[a-z]+;/gi, " ").replace(/\s+/g, " ").trim();
    return extractedText;
  }
};

// src/utils/youtubeTranscript.ts
var YouTubeTranscript = class {
  static extractVideoId(url) {
    const match = url.match(this.YOUTUBE_REGEX);
    return match ? match[1] : null;
  }
  static isYouTubeUrl(url) {
    return this.YOUTUBE_REGEX.test(url);
  }
  static async fetchTranscript(videoId, lang = "en") {
    try {
      const videoPageResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}`);
      if (!videoPageResponse.ok) {
        throw new Error("Failed to fetch video page");
      }
      const videoPageHtml = await videoPageResponse.text();
      const captionsMatch = videoPageHtml.match(/"captions":\s*({[^}]+})/);
      if (!captionsMatch) {
        throw new Error("No captions available for this video");
      }
      const transcriptMatch = videoPageHtml.match(/"captionTracks":\s*(\[[^\]]+\])/);
      if (!transcriptMatch) {
        throw new Error("Could not find transcript data");
      }
      let captionTracks;
      try {
        captionTracks = JSON.parse(transcriptMatch[1]);
      } catch (e) {
        throw new Error("Failed to parse caption tracks");
      }
      let captionTrack = captionTracks.find(
        (track) => {
          var _a;
          return track.languageCode === lang || ((_a = track.languageCode) == null ? void 0 : _a.startsWith(lang));
        }
      );
      if (!captionTrack && captionTracks.length > 0) {
        captionTrack = captionTracks[0];
      }
      if (!captionTrack || !captionTrack.baseUrl) {
        throw new Error("No suitable caption track found");
      }
      const transcriptResponse = await fetch(captionTrack.baseUrl);
      if (!transcriptResponse.ok) {
        throw new Error("Failed to fetch transcript");
      }
      const transcriptXml = await transcriptResponse.text();
      const transcript = this.parseTranscriptXml(transcriptXml);
      return transcript;
    } catch (error) {
      throw new Error(`YouTube transcript error: ${error.message}`);
    }
  }
  static parseTranscriptXml(xml) {
    const textMatches = xml.matchAll(/<text[^>]*start="([^"]*)"[^>]*>(.*?)<\/text>/g);
    const lines = [];
    for (const match of textMatches) {
      const text = match[2].replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/\n/g, " ").trim();
      if (text) {
        lines.push(text);
      }
    }
    return lines.join(" ");
  }
  static async getTranscriptFromUrl(url) {
    const videoId = this.extractVideoId(url);
    if (!videoId) {
      throw new Error("Invalid YouTube URL");
    }
    const languages = ["en", "ru", "auto"];
    for (const lang of languages) {
      try {
        return await this.fetchTranscript(videoId, lang);
      } catch (error) {
        continue;
      }
    }
    throw new Error("Could not fetch transcript in any language");
  }
};
YouTubeTranscript.YOUTUBE_REGEX = /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/;

// src/views/sourceInputModal.ts
var SourceInputModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.urlInput = "";
    this.textInput = "";
    this.isProcessing = false;
    this.textAreaComponent = null;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Source Material" });
    contentEl.createEl("p", {
      text: "Enter a URL (article or YouTube video) or paste the source text directly.",
      cls: "setting-item-description"
    });
    new import_obsidian5.Setting(contentEl).setName("URL").setDesc("Article URL or YouTube video link").addText((text) => {
      text.setPlaceholder("https://example.com/article or https://youtube.com/watch?v=...").setValue(this.urlInput).onChange((value) => {
        this.urlInput = value;
      });
      text.inputEl.style.width = "100%";
    }).addButton((btn) => btn.setButtonText("Parse URL").onClick(async () => {
      await this.handleUrlParse();
    }));
    const divider = contentEl.createEl("div", {
      text: "\u2014 OR \u2014",
      cls: "reading-coach-divider"
    });
    divider.style.textAlign = "center";
    divider.style.margin = "1em 0";
    new import_obsidian5.Setting(contentEl).setName("Source Text").setDesc("Paste the source text directly (or parsed from URL above)").addTextArea((text) => {
      this.textAreaComponent = text;
      text.setPlaceholder("Paste source text here...").setValue(this.textInput).onChange((value) => {
        this.textInput = value;
      });
      text.inputEl.rows = 12;
      text.inputEl.style.width = "100%";
    });
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText("Cancel").onClick(() => {
      this.close();
    })).addButton((btn) => btn.setButtonText("Analyze").setCta().setDisabled(this.isProcessing).onClick(async () => {
      await this.handleSubmit();
    }));
  }
  async handleUrlParse() {
    if (!this.urlInput.trim()) {
      new import_obsidian5.Notice("Please enter a URL");
      return;
    }
    const url = this.urlInput.trim();
    this.isProcessing = true;
    try {
      if (YouTubeTranscript.isYouTubeUrl(url)) {
        new import_obsidian5.Notice("Fetching YouTube transcript...");
        const transcript = await YouTubeTranscript.getTranscriptFromUrl(url);
        this.textInput = transcript;
        if (this.textAreaComponent) {
          this.textAreaComponent.setValue(transcript);
        }
        new import_obsidian5.Notice(`\u2713 Extracted ${transcript.length} characters from YouTube video`);
      } else {
        new import_obsidian5.Notice("Fetching article from URL...");
        const sourceText = await TextExtractor.extractFromUrl(url);
        this.textInput = sourceText;
        if (this.textAreaComponent) {
          this.textAreaComponent.setValue(sourceText);
        }
        new import_obsidian5.Notice(`\u2713 Extracted ${sourceText.length} characters from article`);
      }
    } catch (error) {
      new import_obsidian5.Notice(`Error: ${error.message}`);
    } finally {
      this.isProcessing = false;
    }
  }
  async handleSubmit() {
    if (this.isProcessing) {
      return;
    }
    if (this.textInput.trim()) {
      const sourceText = TextExtractor.extractFromText(this.textInput.trim());
      if (sourceText.length < 50) {
        new import_obsidian5.Notice("Source text is too short. Please provide more content.");
        return;
      }
      this.close();
      this.onSubmit(sourceText);
    } else {
      new import_obsidian5.Notice("Please provide source text or parse a URL first");
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var ReadingCoachPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.depthCheckMode = new DepthCheckMode(this);
    this.connectionFinderMode = new ConnectionFinderMode(this);
    this.addRibbonIcon("book-open", "Reading Coach", () => {
      new import_obsidian6.Notice("Reading Coach: Use command palette to select a mode");
    });
    this.addCommand({
      id: "depth-check",
      name: "Reading Coach: Depth Check",
      callback: async () => {
        await this.runDepthCheck();
      }
    });
    this.addCommand({
      id: "connection-finder",
      name: "Reading Coach: Connection Finder",
      callback: async () => {
        await this.runConnectionFinder();
      }
    });
    this.addSettingTab(new ReadingCoachSettingTab(this.app, this));
    console.log("Reading Coach plugin loaded");
  }
  onunload() {
    console.log("Reading Coach plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async runDepthCheck() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!activeView) {
      new import_obsidian6.Notice("Please open a note first");
      return;
    }
    const userNotes = activeView.editor.getValue();
    if (!userNotes) {
      new import_obsidian6.Notice("Current note is empty");
      return;
    }
    new SourceInputModal(this.app, async (sourceText) => {
      await this.depthCheckMode.execute(sourceText, userNotes);
    }).open();
  }
  async runConnectionFinder() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
    if (!activeView) {
      new import_obsidian6.Notice("Please open a note first");
      return;
    }
    const userNotes = activeView.editor.getValue();
    if (!userNotes) {
      new import_obsidian6.Notice("Current note is empty");
      return;
    }
    new SourceInputModal(this.app, async (sourceText) => {
      await this.connectionFinderMode.execute(sourceText, userNotes);
    }).open();
  }
};
